global:
  smtp_smarthost: "localhost:587"
  smtp_from: "alertmanager@walrex.com"
  smtp_auth_username: ""
  smtp_auth_password: ""
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://localhost:5001/webhook"
        send_resolved: true

  - name: "slack-notifications"
    slack_configs:
      - api_url: "YOUR_SLACK_WEBHOOK_URL"
        channel: "#alerts"
        title: "Walrex Monolith Alert"
        text: "Summary: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
        send_resolved: true

  - name: "email-notifications"
    email_configs:
      - to: "admin@walrex.com"
        subject: "Walrex Alert: {{ .GroupLabels.alertname }}"
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
