global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuración de reglas de alertas
rule_files:
  - "alert_rules.yml"

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Configuración de targets para recolectar métricas
scrape_configs:
  # Métricas del propio Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de la aplicación Walrex Monolith
  - job_name: "walrex-monolith"
    static_configs:
      - targets: ["api-monolith:8088"]
    scrape_interval: 15s
    metrics_path: "/actuator/prometheus"
    scheme: http
    basic_auth:
      username: ""
      password: ""

  # Métricas del sistema (Node Exporter)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de contenedores Docker (cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de Loki
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de Grafana
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de Promtail
  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
    scrape_interval: 15s
    metrics_path: "/metrics"

  # Métricas de Alertmanager
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    scrape_interval: 15s
    metrics_path: "/metrics"

# Configuración de almacenamiento
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB

# Configuración de queries
query:
  timeout: 30s
  max_concurrent: 20
  max_samples: 50000000
