spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:erp_tlm_2021}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
