spring:
  application:
    name: module-role
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
server:
  port: 8083

security:
  jwt:
    secret-key: l7kP8lgYRt/PyIh/tBDYlg4QWCLf2RSOJ8oLPNV6O34=
    expiration-time: 36000
    refresh-toke:
      expiration: 604800000