server:
  port: 8088
spring:
  application:
    name: module-core
  cache:
    type: REDIS
    redis:
      time-to-live: 15m
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      timeout: 2000ms
      time-to-live: 15m
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: admin
    password: password123
    virtual-host: /
    connection-timeout: 60000
    requested-heartbeat: 60
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  main:
    web-application-type: reactive
    banner-mode: console
  resilience4j:
    circuitbreaker:
      instances:
        kafkaProducer:
          failureRateThreshold: 50
          waitDurationInOpenState: 5000
          permittedNumberOfCallsInHalfOpenState: 2
          slidingWindowSize: 5
          minimumNumberOfCalls: 2
          automaticTransitionFromOpenToHalfOpenEnabled: true
          recordExceptions:
            - java.io.IOException
            - java.util.concurrent.TimeoutException
            - org.apache.kafka.common.errors.TimeoutException
        guiaRemisionKafkaProducer:
          failureRateThreshold: 60
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          automaticTransitionFromOpenToHalfOpenEnabled: true
          recordExceptions:
            - java.io.IOException
            - java.util.concurrent.TimeoutException
            - org.apache.kafka.common.errors.TimeoutException
            - org.apache.kafka.common.errors.NetworkException
            - org.apache.kafka.common.errors.RetriableException
  security:
    enabled: false
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: false
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
    circuitbreaker:
      resilience4j:
        configs:
          default:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
            permittedNumberOfCallsInHalfOpenState: 5
            registerHealthIndicator: true
            timeLimiterConfig:
              timeoutDuration: 10s
            recordExceptions:
              - java.util.concurrent.TimeoutException
              - org.springframework.web.reactive.function.client.WebClientResponseException
            ignoreExceptions:
              - java.lang.IllegalArgumentException
        instances:
          kafkaProducer:
            timeoutDuration: 5s
            baseConfig: default
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 20
            timeLimiterConfig:
              timeoutDuration: 10s
            waitDurationInOpenState: 30000
            automaticTransitionFromOpenToHalfOpenEnabled: true
          articleProducerKafka:
            timeoutDuration: 5s
            baseConfig: default
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 20
            timeLimiterConfig:
              timeoutDuration: 10s
            waitDurationInOpenState: 30000
            automaticTransitionFromOpenToHalfOpenEnabled: true
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/erp_tlm_2021
    username: postgres
    password: 12345
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      auto.create.topics.enabled: true
      schema.registry.url: http://127.0.0.1:8081
      security:
        protocol: PLAINTEXT
    consumer:
      group-id: rol-service-group
      auto-offset-reset: latest #earliest asegura leer desde el principio
      enable-auto-commit: true
      session-timeout-ms: 60000
      heartbeat-interval-ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        max.partition.fetch.bytes: 10485760
        schema.registry.url: http://127.0.0.1:8081
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8081
        auto.registry.schemas: true
        use.latest.version: true
        specific.avro.reader: true
  totp:
    code:
      digits: 6
    time:
      period: 300
  mail:
    host: mail.texlamerced.com
    port: 465
    username: raybar@texlamerced.com
    password: Sistemas2023@.
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
        transport:
          protocol: smtp
      from: noreply@texlamerced.com
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  flyway:
    enabled: true
    url: jdbc:postgresql://127.0.0.1:5432/erp_tlm_2021
    user: postgres
    password: 12345
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: true
  aop:
    auto: true
    proxy-target-class: true
websocket:
  module:
    port: 5555
    max-connections: 100
    ping-interval: 30000
    ping-timeout: 90000
    upgrade-timeout: 15000
    max-frame-payload-length: 32768
    allow-custom-requests: false
    cors:
      origin: "*"
flyway:
  modules:
    enabled: true
    verbose: true
reactor:
  tools:
    agent:
      enabled: false
security:
  jwt:
    secret-key: l7kP8lgYRt/PyIh/tBDYlg4QWCLf2RSOJ8oLPNV6O34=
    expiration-time: 36000
    refresh-toke:
      expiration: 604800000
kafka:
  topics:
    password-recovery: "email-requests-topic"
    rol-details: "detail-rol"
    response-rol-details: "details-rol-response"
    role-and-details: "role_and_detail"
    get-info-articulos: "articulo-by-code"
    almacen:
      create-ingreso-ajuste: ajuste-ingreso-message
      create-ingreso-ajuste-response: ajuste-ingreso-response
      create-comprobante-guia-remision: create-comprobante-guia-remision
      response-create-guia-remision-remitente: response-create-comprobante-grr
rabbitmq:
  almacen:
    exchange:
      devolucion: "devolucion.exchange"
app:
  mail:
    templates:
      recovery: "reset-password.html"
# Configuración OpenAPI/Swagger
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.walrex
  paths-to-match: /api/**, /v1/**, /**
  group-configs:
    - group: motivos-devolucion
      display-name: "Motivos de Devolución"
      paths-to-match: /almacen/motivos-devolucion/**
lycet:
  api:
    token: EXnPrun0IjhqwyZaNSWLZpeJ9y1ktZOJ
    base-url: http://localhost:8880/api/v1
    endpoint-despatch: /despatch/send
    timeout: 30
logging:
  level:
    reactor.tools: OFF
    com.walrex: DEBUG
    com.walrex.gateway: TRACE
    com.walrex.module_ecomprobantes: DEBUG
    com.walrex.module_driver: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.reactor: OFF
    com.corundumstudio.socketio: DEBUG
    # R2DBC logging para debugging de consultas SQL
    io.r2dbc.postgresql: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
  dynamic:
    enabled: true
    modules: almacen,users,articulos,ecomprobantes,role,gateway,core,mailing,partidas
    default-level: DEBUG
    error-level: ERROR
