spring:
  cache:
    type: REDIS
    redis:
      time-to-live: 15m
  data:
    redis:
      host: 192.168.1.90
      port: 6379
      password:
      database: 0
      timeout: 60000ms
      connect-timeout: 5000ms
  r2dbc:
    url: r2dbc:postgresql://192.168.1.90:5432/erp_tlm_2021
    username: postgres
    password: 12345
  kafka:
    bootstrap-servers: 192.168.1.90:9092
    properties:
      auto.create.topics.enabled: true
      schema.registry.url: http://192.168.1.90:8081
      security:
        protocol: PLAINTEXT
    consumer:
      group-id: rol-service-group
      auto-offset-reset: latest #earliest asegura leer desde el principio
      enable-auto-commit: true
      session-timeout-ms: 60000
      heartbeat-interval-ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        max.partition.fetch.bytes: 10485760
        schema.registry.url: http://192.168.1.90:8081
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://192.168.1.90:8081
        auto.registry.schemas: true
        use.latest.version: true
        specific.avro.reader: true
  totp:
    code:
      digits: 6
    time:
      period: 300
  mail:
    host: mail.texlamerced.com
    port: 465
    username: raybar@texlamerced.com
    password: Sistemas2023@.
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
        transport:
          protocol: smtp
      from: noreply@texlamerced.com
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  flyway:
    enabled: true
    url: jdbc:postgresql://192.168.1.90:5432/erp_tlm_2021
    user: postgres
    password: 12345
    locations: classpath:db/migration
    baseline-version: 0
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
  aop:
    auto: true
    proxy-target-class: true
flyway:
  modules:
    enabled: true
    verbose: true
security:
  jwt:
    secret-key: l7kP8lgYRt/PyIh/tBDYlg4QWCLf2RSOJ8oLPNV6O34=
    expiration-time: 36000
    refresh-toke:
      expiration: 604800000
kafka:
  topics:
    password-recovery: "email-requests-topic"
    rol-details: "detail-rol"
    response-rol-details: "details-rol-response"
    role-and-details: "role_and_detail"
    get-info-articulos: "articulo-by-code"
    almacen:
      create-ingreso-ajuste: ajuste-ingreso-message
      create-ingreso-ajuste-response: ajuste-ingreso-response
      create-comprobante-guia-remision: create-comprobante-guia-remision
app:
  mail:
    templates:
      recovery: "reset-password.html"
