spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: false
  resilience4j:
    circuitbreaker:
      instances:
        kafkaProducer:
          failureRateThreshold: 50
          waitDurationInOpenState: 5000
          permittedNumberOfCallsInHalfOpenState: 2
          slidingWindowSize: 5
          minimumNumberOfCalls: 2
          automaticTransitionFromOpenToHalfOpenEnabled: true
          recordExceptions:
            - java.io.IOException
            - java.util.concurrent.TimeoutException
            - org.apache.kafka.common.errors.TimeoutException
            - org.apache.kafka.common.errors.NetworkException
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:erp_tlm_2021}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER_0:localhost:9094}
    properties:
      auto.create.topics.enabled: true
      security:
        protocol: PLAINTEXT
      schema.registry.url: http://${SCHEMA_REGISTRY_SERVER:localhost}:${SCHEMA_REGISTRY_PORT:8081}
    consumer:
      group-id: mailing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://${SCHEMA_REGISTRY_SERVER:localhost}:${SCHEMA_REGISTRY_PORT:8081}
        auto.registry.schemas: true
        max.partition.fetch.bytes: 10485760
        specific.avro.reader: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://${SCHEMA_REGISTRY_SERVER:localhost}:${SCHEMA_REGISTRY_PORT:8081}
        auto.registry.schemas: true
        use.latest.version: true
        specific.avro.reader: true